### ISSUE TITLE
IP Infrigements

### ISSUE THREAD

**Issue by sirhill** [MtPelerin/bridge-v2#6]
This repository contains code taken from the original repository [C-Layer](https://github.com/c-layer/contracts) without the copyrights or the consent of the author.

Please do not use it!

PS: Issues keep being deleted on this repository:
- [issue 1](https://github.com/MtPelerin/bridge-v2/issues/1)
- [issue 2](https://github.com/MtPelerin/bridge-v2/issues/2)
- [issue 3](https://github.com/MtPelerin/bridge-v2/issues/3)
- [issue 4](https://github.com/MtPelerin/bridge-v2/issues/4)
- [issue 5](https://github.com/MtPelerin/bridge-v2/issues/5)

**Comment by yann-gerardi** [comment]
This issue is incorrect, unfounded and unsubstantiated. Moreover, Github (and any other social media platform) is not the appropriate channel for your claim. Issue closed.
